base_path: /scratch/project_465001979/ct_data/kidney/
tuh_only: false
tuh_extra_data: true

batch_size: 1
train_workers: 4
val_workers: 2
spacing: [2.0, 2.0, 2.0] #[2.0, 0.84, 0.84]
#patch_size: [1, 500, 500]
intensity_min: -150
intensity_max: 250
axial_crop: 250
depth_crop: 300
prefetch_factor: 2
name: 2d_slice

cache_dir: /scratch/project_465002884/monai_cache/sp${dataloader.spacing[0]}_${dataloader.spacing[1]}_crop${dataloader.depth_crop}_ax${dataloader.axial_crop}