hydra:
  run:
    dir: /scratch/project_465002884/results/${experiment}/${model}/${dataloader.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - dataloader/2d_slice #dataloader/3d_scan or /2d_slice

experiment: 3D #ABMIL, compass, FocusMIL and now 3D
model: resnet18_3D #_3D
norm_layer: group
pretrained: imagenet # imagenet/compass
compass_filter : True
distributed: False

loss: bce #bce/depth
loss_kwargs: {}

epochs: 150
weight_decay: 5e-4
patch_mode: False
mode: 3D #3D, 2D

negative_instance_supervision: False

checkpoint_path: null
notebook_eval: False
seed: 42 #42 52 62


